export const COLLECTIONS = {
  users: 'users',
  leaders: 'leaders',
  leaderLandingPages: 'leaderLandingPages',
  prospects: 'prospects',
  leadActivities: 'leadActivities',
  referralCodes: 'referralCodes',
  recommendationCodes: 'recommendationCodes',
  slugs: 'slugs',
  academyMaterials: 'academyMaterials',
  academyTests: 'academyTests',
  academyTestAttempts: 'academyTestAttempts',
  academyMaterialEngagements: 'academyMaterialEngagements',
  actionTasks: 'actionTasks',
  actionTaskProgress: 'actionTaskProgress',
  teamActionMaps: 'teamActionMaps',
  teamActionMapReviews: 'teamActionMapReviews',
  teams: 'teams',
  leaderInviteCodes: 'leaderInviteCodes',
  teamMembers: 'teamMembers',
  groupActivationRequests: 'groupActivationRequests',
  referralRewards: 'referralRewards',
  referralPayoutRequests: 'referralPayoutRequests',
  teamReminders: 'teamReminders',
  recognitionWeeklySnapshots: 'recognitionWeeklySnapshots',
  recognitionMonthlyPrizes: 'recognitionMonthlyPrizes',
  teamRecognitions: 'teamRecognitions',
  teamSalesGoals: 'teamSalesGoals',
  teamSalesReports: 'teamSalesReports',
} as const

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS]
