/** Ciudades principales por código ISO de país, ordenadas alfabéticamente. */

function sortCities(cities: string[]): string[] {
  return [...cities].sort((a, b) => a.localeCompare(b, 'es', { sensitivity: 'base' }))
}

const CITIES_BY_COUNTRY_RAW: Record<string, string[]> = {
  AE: ['Abu Dabi', 'Dubái', 'Sharjah'],
  AR: [
    'Bahía Blanca',
    'Buenos Aires',
    'Córdoba',
    'La Plata',
    'Mar del Plata',
    'Mendoza',
    'Rosario',
    'Salta',
    'San Miguel de Tucumán',
  ],
  AT: ['Graz', 'Innsbruck', 'Linz', 'Salzburgo', 'Viena'],
  AU: ['Adelaida', 'Brisbane', 'Canberra', 'Melbourne', 'Perth', 'Sídney'],
  BE: ['Amberes', 'Brujas', 'Bruselas', 'Gante', 'Lieja'],
  BO: ['Cochabamba', 'El Alto', 'La Paz', 'Oruro', 'Santa Cruz de la Sierra', 'Sucre'],
  BR: [
    'Belém',
    'Belo Horizonte',
    'Brasília',
    'Curitiba',
    'Fortaleza',
    'Manaus',
    'Porto Alegre',
    'Recife',
    'Rio de Janeiro',
    'Salvador',
    'São Paulo',
  ],
  CA: ['Calgary', 'Montreal', 'Ottawa', 'Toronto', 'Vancouver'],
  CH: ['Basilea', 'Berna', 'Ginebra', 'Lausana', 'Zúrich'],
  CL: ['Antofagasta', 'Concepción', 'La Serena', 'Santiago', 'Temuco', 'Valparaíso', 'Viña del Mar'],
  CN: ['Beijing', 'Cantón', 'Shanghái', 'Shenzhen'],
  CO: [
    'Barranquilla',
    'Bogotá',
    'Bucaramanga',
    'Cali',
    'Cartagena',
    'Cúcuta',
    'Medellín',
    'Pereira',
  ],
  CR: ['Alajuela', 'Cartago', 'Heredia', 'Liberia', 'San José'],
  CU: ['Camagüey', 'Holguín', 'La Habana', 'Santiago de Cuba'],
  DE: ['Berlín', 'Colonia', 'Fráncfort', 'Hamburgo', 'Múnich', 'Stuttgart'],
  DK: ['Aarhus', 'Copenhague', 'Odense'],
  DO: ['La Romana', 'Puerto Plata', 'Punta Cana', 'Santiago de los Caballeros', 'Santo Domingo'],
  EC: ['Ambato', 'Cuenca', 'Guayaquil', 'Manta', 'Quito'],
  EG: ['Alejandría', 'El Cairo', 'Giza'],
  ES: [
    'Barcelona',
    'Bilbao',
    'Madrid',
    'Málaga',
    'Murcia',
    'Palma',
    'Sevilla',
    'Valencia',
    'Zaragoza',
  ],
  FI: ['Espoo', 'Helsinki', 'Tampere', 'Turku'],
  FR: ['Lyon', 'Marsella', 'Niza', 'París', 'Toulouse'],
  GB: ['Birmingham', 'Edimburgo', 'Glasgow', 'Liverpool', 'Londres', 'Manchester'],
  GR: ['Atenas', 'Salónica'],
  GT: ['Antigua Guatemala', 'Ciudad de Guatemala', 'Quetzaltenango'],
  HN: ['La Ceiba', 'San Pedro Sula', 'Tegucigalpa'],
  IE: ['Cork', 'Dublín', 'Galway'],
  IL: ['Haifa', 'Jerusalén', 'Tel Aviv'],
  IN: ['Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Bombay', 'Pune'],
  IT: ['Florencia', 'Milán', 'Nápoles', 'Roma', 'Turín', 'Venecia'],
  JP: ['Kioto', 'Osaka', 'Tokio', 'Yokohama'],
  KE: ['Mombasa', 'Nairobi'],
  KR: ['Busan', 'Incheon', 'Seúl'],
  MA: ['Casablanca', 'Fez', 'Marrakech', 'Rabat'],
  MX: [
    'Cancún',
    'Ciudad de México',
    'Guadalajara',
    'León',
    'Monterrey',
    'Puebla',
    'Querétaro',
    'Tijuana',
  ],
  NG: ['Abuya', 'Ibadán', 'Kano', 'Lagos'],
  NI: ['León', 'Managua'],
  NL: ['Ámsterdam', 'La Haya', 'Róterdam', 'Utrecht'],
  NO: ['Bergen', 'Oslo', 'Stavanger', 'Trondheim'],
  NZ: ['Auckland', 'Christchurch', 'Wellington'],
  PA: ['Ciudad de Panamá', 'Colón', 'David'],
  PE: [
    'Arequipa',
    'Cajamarca',
    'Chiclayo',
    'Cusco',
    'Huancayo',
    'Iquitos',
    'Lima',
    'Piura',
    'Trujillo',
  ],
  PL: ['Cracovia', 'Gdansk', 'Varsovia', 'Wroclaw'],
  PR: ['Bayamón', 'Ponce', 'San Juan'],
  PT: ['Braga', 'Coímbra', 'Lisboa', 'Oporto'],
  PY: ['Asunción', 'Ciudad del Este', 'Encarnación'],
  QA: ['Doha'],
  RO: ['Bucarest', 'Cluj-Napoca', 'Timisoara'],
  RU: ['Moscú', 'San Petersburgo'],
  SA: ['Jeddah', 'La Meca', 'Riad'],
  SE: ['Gotemburgo', 'Malmö', 'Estocolmo'],
  SV: ['San Miguel', 'San Salvador', 'Santa Ana'],
  TR: ['Ankara', 'Estambul', 'Izmir'],
  UA: ['Járkov', 'Kiev', 'Odesa'],
  US: [
    'Chicago',
    'Houston',
    'Los Ángeles',
    'Miami',
    'Nueva York',
    'Orlando',
    'San Francisco',
    'Washington D. C.',
  ],
  UY: ['Montevideo', 'Punta del Este', 'Salto'],
  VE: ['Barquisimeto', 'Caracas', 'Maracaibo', 'Valencia'],
  ZA: ['Ciudad del Cabo', 'Durban', 'Johannesburgo', 'Pretoria'],
}

export const CITIES_BY_COUNTRY: Record<string, string[]> = Object.fromEntries(
  Object.entries(CITIES_BY_COUNTRY_RAW).map(([code, cities]) => [code, sortCities(cities)]),
)

export function getCitiesForCountry(countryCode: string): string[] {
  const normalized = countryCode.trim().toUpperCase()
  return CITIES_BY_COUNTRY[normalized] ?? []
}
